
function dataMemory_config(this_block)

  % Revision History:
  %
  %   08-Apr-2019  (18:12 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Users\Hashir\Desktop\project-1-ecte432-hzs\Single cycle mips\datamem.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('dataMemory');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('address');
  this_block.addSimulinkInport('WriteData');
  this_block.addSimulinkInport('memRead');
  this_block.addSimulinkInport('memWrite');

  this_block.addSimulinkOutport('readData');

  readData_port = this_block.port('readData');
  readData_port.setType('UFix_32_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('address').width ~= 32);
      this_block.setError('Input data type for port "address" must have width=32.');
    end

    if (this_block.port('WriteData').width ~= 32);
      this_block.setError('Input data type for port "WriteData" must have width=32.');
    end

    if (this_block.port('memRead').width ~= 1);
      this_block.setError('Input data type for port "memRead" must have width=1.');
    end

    this_block.port('memRead').useHDLVector(false);

    if (this_block.port('memWrite').width ~= 1);
      this_block.setError('Input data type for port "memWrite" must have width=1.');
    end

    this_block.port('memWrite').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('datamem.vhd');

return;


